### ISSUE TITLE
 System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by pmcfernandes** [coderrapp/codeRR.Client#13]
I getting this error in my OneTrueError server instance. I see is a error from OneTrueError.Client 

System.NullReferenceException: Object reference not set to an instance of an object. at OneTrueError.Client.Converters.ObjectToContextCollectionConverter.IsFilteredOut(Object instance) at OneTrueError.Client.Converters.ObjectToContextCollectionConverter.ReflectValue(String propertyName, Object value, ContextCollectionDTO contextCollection, List`1 path) at OneTrueError.Client.Converters.ObjectToContextCollectionConverter.ReflectObject(Object instance, String prefix, ContextCollectionDTO contextCollection, List`1 path) at OneTrueError.Client.Converters.ObjectToContextCollectionConverter.ReflectObject(Object instance, String prefix, ContextCollectionDTO contextCollection, List`1 path) at OneTrueError.Client.Converters.ObjectToContextCollectionConverter.Convert(String collectionName, Object instance)
--

**Comment by jgauffin** [comment]
Thank you for your report.

Try the latest version of the client version.
