### ISSUE TITLE
An error occurred while downloading package 'Newtonsoft.Json.10.0.3 

### ISSUE THREAD

**Issue by ruisantos78** [coderrapp/codeRR.Client#14]
Error installing the client over NuGet because the package 'Newtonsoft.Json.10.0.3' not found...

Any chances to use prior version like  'Newtonsoft.Json.9.0.1' ?

```
PM> Install-Package Coderr.Client -Version 1.0.18
Attempting to gather dependencies information for package 'Coderr.Client.1.0.18' with respect to project 'WindowsFormsApplication2', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'Coderr.Client.1.0.18' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Coderr.Client.1.0.18'
Resolved actions to install package 'Coderr.Client.1.0.18'
Removed package 'Newtonsoft.Json.9.0.1' from 'packages.config'
Successfully uninstalled 'Newtonsoft.Json.9.0.1' from WindowsFormsApplication2
Install failed. Rolling back...
Package 'Newtonsoft.Json.10.0.3 : ' does not exist in project 'WindowsFormsApplication2'
Package 'Newtonsoft.Json.9.0.1' already exists in folder 'e:\usuários\rcsantos\documents\visual studio 2015\Projects\WindowsFormsApplication2\packages'
Added package 'Newtonsoft.Json.9.0.1' to 'packages.config'
Executing script file 'e:\usuários\rcsantos\documents\visual studio 2015\Projects\WindowsFormsApplication2\packages\Newtonsoft.Json.9.0.1\tools\install.ps1'
Package 'Newtonsoft.Json.10.0.3 : ' does not exist in folder 'e:\usuários\rcsantos\documents\visual studio 2015\Projects\WindowsFormsApplication2\packages'
Install-Package : An error occurred while downloading package 'Newtonsoft.Json.10.0.3 : ' from source 'https://www.nuget.org/api/v2/'.
At line:1 char:1
+ Install-Package Coderr.Client -Version 1.0.18
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
```

**Comment by jgauffin** [comment]
10.0.3 is the second latest version as you can see here: https://www.nuget.org/packages/Newtonsoft.Json/

If you would like to use 9.0.1 you need to add an assemblyBinding in your app/web.config. Check the second answer in this stackoverflow question: https://stackoverflow.com/questions/38671641/could-not-load-file-or-assembly-newtonsoft-json-version-9-0-0-0-culture-neutr

(change to 9.0.1 in the assemblyBinding)

**Comment by ruisantos78** [comment]
I know... but has been a lot of issues about the instalation of versions
10+ of  Newtonsoft.Json <https://www.nuget.org/packages/Newtonsoft.Json/>...
even now you can install the Coderr.Client over NuGet because of it....

I'm just asking to use a real stable version of it until a future version
be real stable,

Just try install it and you will see  " Install-Package Newtonsoft.Json
-Version 10.0.3 "




Em qua, 14 de mar de 2018 às 15:34, Jonas Gauffin <notifications@github.com>
escreveu:

**Comment by jgauffin** [comment]
Can you explain what kind of trouble you have with v10?

**Comment by ruisantos78** [comment]
It simple don't install...  I don't know if is somethine about nuget or
something else...

I always need to change to 9.x version

Em 15 de mar de 2018 4:36 AM, "Jonas Gauffin" <notifications@github.com>
escreveu:

**Comment by jgauffin** [comment]
Can you show me what kind of error that you get if you try to update Newtonsoft.Json through the package manager? It's hard for me to help you otherwise.

**Comment by ruisantos78** [comment]
The error is on the log when I open the issue:

*PM> Install-Package Coderr.Client -Version 1.0.18*
Attempting to gather dependencies information for package
'Coderr.Client.1.0.18' with respect to project
'WindowsFormsApplication2', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'Coderr.Client.1.0.18'
with DependencyBehavior 'Lowest'
Resolving actions to install package 'Coderr.Client.1.0.18'
Resolved actions to install package 'Coderr.Client.1.0.18'
Removed package 'Newtonsoft.Json.9.0.1' from 'packages.config'
Successfully uninstalled 'Newtonsoft.Json.9.0.1' from WindowsFormsApplication2
Install failed. Rolling back...
Package 'Newtonsoft.Json.10.0.3 : ' does not exist in project
'WindowsFormsApplication2'
Package 'Newtonsoft.Json.9.0.1' already exists in folder
'e:\usuários\rcsantos\documents\visual studio
2015\Projects\WindowsFormsApplication2\packages'
Added package 'Newtonsoft.Json.9.0.1' to 'packages.config'
Executing script file 'e:\usuários\rcsantos\documents\visual studio
2015\Projects\WindowsFormsApplication2\packages\Newtonsoft.Json.9.0.1\tools\install.ps1'*Package
'Newtonsoft.Json.10.0.3 : ' does not exist in folder
'e:\usuários\rcsantos\documents\visual studio
2015\Projects\WindowsFormsApplication2\packages'
Install-Package : An error occurred while downloading package
'Newtonsoft.Json.10.0.3 : ' from source 'https://www.nuget.org/api/v2/
<https://www.nuget.org/api/v2/>'.*
At line:1 char:1
+ Install-Package Coderr.Client -Version 1.0.18
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId :
NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand




Em qui, 15 de mar de 2018 às 10:20, Jonas Gauffin <notifications@github.com>
escreveu:
