### ISSUE TITLE
Create a .NET Core library (for ASP.NET Core)

### ISSUE THREAD

**Issue by gauffininteractive** [coderrapp/codeRR.Client#7]
This issue is dependent of #6.

An ASP.NET Core package to catch exceptions. 

Might want to take a look at the Diagnostics middleware? https://github.com/aspnet/Diagnostics

**Comment by gauffininteractive** [comment]
Which part are you referring to? Diagnostics might be a much better extension point to be able to catch the exceptions with context info

**Comment by pichardoSoftware** [comment]
Ok, what can I help you with?

**Comment by jgauffin** [comment]
Creating a .NET Core version of the base library (https://github.com/gauffininteractive/onetrueerror.client/tree/master/client) would be a really great start :)

i.e. staring with issue #6

**Comment by pichardoSoftware** [comment]
Ok

**Comment by jgauffin** [comment]
There is now a .NET Standard library and a Core MVC library
